site_name: The Man of The Gun
site_description: A dark, narrative-driven action game
site_author: MindShield Studios
site_url: https://tmotg.mindshield.ai

extra:
  meta:
    - name: 'google-site-verification'
      content: 'i7-uLw3KgNwO1WkIvmnSHWRmecGQGxSruRyE7Ws9sKs'

  favicon: 'favicon.ico'

theme:
  name: 'simple-blog'

nav:
  - Home: index.md
  - About the Game:
      - Story:
          - Introduction: about/story.md
          - Prologue: about/echoes-of-the-unseen.md
      - Characters: about/characters.md
  - Media:
      - Trailers: media/trailers.md
      - Gallery: media/gallery.md
      - Development Updates: media/dev-updates.md
  - Contact: contact.md
  - Main Site: https://themanofofthegun.com

plugins:
  - search
  - redirects:
      redirect_maps:
        about/Echoes of the Unseen.md: about/echoes-of-the-unseen.md

extra_css:
  - assets/css/extra.css

extra_javascript:
  - assets/js/banner.js

markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: false
