site_name: The Man of The Gun
site_description: A dark, narrative-driven action game
site_author: MindShield Studios
site_url: https://tmotg.mindshield.ai

extra:
  meta:
    - name: 'google-site-verification'
      content: 'i7-uLw3KgNwO1WkIvmnSHWRmecGQGxSruRyE7Ws9sKs'

  favicon: 'favicon.ico'

theme:
  name: 'simple-blog'
  custom_dir: docs/overrides

nav:
  - Home: index.md
  - Story:
      - Story: story/index.md
      - Prologue: story/prologue.md
      - Chapter 1: story/chapter-01-the-fractured-mirror.md
      - Chapter 2: story/chapter-02-threads-of-reality.md
      - Chapter 3: story/chapter-03-shadows-of-envy.md
      - Chapter 4: story/chapter-04-the-weight-of-conviction.md
      - Chapter 5: story/chapter-05-descent-into-the-abyss.md
      - Chapter 6: story/chapter-06-echoes-in-the-void.md
      - Chapter 7: story/chapter-07-shiniza-yakavazes-paradox.md
  - Characters: about/characters.md
  - Media:
      - Trailers: media/trailers.md
      - Gallery: media/gallery.md
      - Development Updates: media/dev-updates.md
  - Contact: contact.md
  - Main Site: https://themanofthegun.com

plugins:
  - search
  - redirects:
      redirect_maps:
        about/Echoes of the Unseen.md: about/echoes-of-the-unseen.md

extra_css:
  - assets/css/extra.css

markdown_extensions:
  - admonition
  - codehilite
  - toc:
      permalink: false
